config/routes.rb
Currencies::Application.routes.draw do
  devise_for :users

  root :to => 'currencies#index'

  resources :currencies, :only => :index do
    collection do
      get 'remaining'
    end
  end

  resources :countries, :only => [:show, :update]
  resources :trips, :only => [:index, :new, :create]

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :country, :inverse_of => :appointments
  belongs_to :user

  attr_accessible :country_id

  validates :country_id, :presence => true, :uniqueness => { :scope => :user_id }
  validates :user_id, :presence => true

  def self.by_currency_name(name)
    joins(:country => :currency).where('currencies.name' => name)
  end
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :country_trips, :dependent => :destroy, :inverse_of => :country
  has_many :appointments, :dependent => :destroy, :inverse_of => :country

  belongs_to :currency

  default_scope order('name ASC')

  attr_accessible :currency, :name, :code

  validates :currency_id, :presence => true
  validates :name, :presence => true
  validates :code, :presence => true, :uniqueness => true

  def self.by_currency_name(name)
    joins(:currency).where('currencies.name' => name)
  end
end

app/models/country_trip.rb
class CountryTrip < ActiveRecord::Base
  belongs_to :country, :inverse_of => :country_trips
  belongs_to :trip

  attr_accessible :country_id

  validates :country_id, :presence => true,
                         :uniqueness => { :scope => :trip_id }

  after_create :create_appointment

  def self.country_count(user)
    count(:country_id, :distinct => true, :joins => :trip, :conditions => { 'trips.user_id' => user.id })
  end

  private

  def create_appointment
    appointment = Appointment.new
    appointment.user = trip.user
    appointment.country = country
    appointment.save
  end
end

app/models/currency.rb
class Currency < ActiveRecord::Base
  extend GroupedByNameCurrencies

  has_many :countries, :dependent => :destroy

  default_scope order('name ASC')

  attr_accessible :name, :code

  validates :name, :presence => true
  validates :code, :presence => true, :uniqueness => true
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  has_many :country_trips, :dependent => :destroy
  has_many :countries, :through => :country_trips

  belongs_to :user

  default_scope order('created_at DESC')

  attr_accessible :description, :completed_at, :country_trips_attributes

  accepts_nested_attributes_for :country_trips, :reject_if => :all_blank

  validates :user_id, :presence => true
  validates :description, :presence => true
  validates :completed_at, :presence => true

  def self.dates(user)
    unscoped.select('DISTINCT completed_at').
             where('user_id' => user.id).
             order('completed_at ASC').
             map &:completed_at
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :appointments, :dependent => :destroy
  has_many :countries, :through => :appointments
  has_many :trips, :dependent => :destroy

  devise :database_authenticatable, :registerable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :appointments_attributes

  accepts_nested_attributes_for :appointments, :allow_destroy => true, :reject_if => :all_blank

  protected

  def password_required?
    !persisted? || password.present? || password_confirmation.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :set_currency_name
  before_filter :build_appointments

  def show
  end

  def update
    if current_user.update_attributes params[:user]
      redirect_to country_url(@currency_name), :notice => 'List successfully changed.'
    else
      render :show
    end
  end

  private

  def set_currency_name
    @currency_name = params[:id].strip
  end

  def build_appointments
    countries = Country.by_currency_name(@currency_name).includes(:currency)
    appointments = current_user.appointments.by_currency_name(@currency_name).includes(:country => :currency)

    remaining_countries = countries - appointments.map(&:country)
    remaining_appointments = remaining_countries.map { |c| c.appointments.build }

    @appointments = (appointments + remaining_appointments).sort_by { |a| a.country.name }
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_filter :authenticate_user!, :only => :remaining

  def index
    @currencies = Currency.grouped_by_name current_user
  end

  def remaining
    @currencies = Currency.grouped_by_name current_user, :only_remaining => true
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :prepare_summary, :only => :index
  before_filter :build_country_trips, :only => [:new, :create]

  def index
    @trips = current_user.trips.includes :countries
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = current_user.trips.build params[:trip]

    if @trip.save
      redirect_to trips_url, :notice => "Trip successfully added."
    else
      render :action => 'new'
    end
  end

  private

  def prepare_summary
    @summary = { :visited_countries => CountryTrip.country_count(current_user),
                 :dates => Trip.dates(current_user) }
  end

  def build_country_trips
    @country_trips = Country.all.map { |c| c.country_trips.build }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
  def appointment_check_box_options(appointment)
    [{ :checked => appointment.persisted?, :class => 'country' }, appointment.country_id, '']
  end

  def country_label(country)
    "#{h country.name} #{content_tag :span, h(country.currency.code)}".html_safe
  end
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
  def currency_description
    if action_name == 'remaining'
      render 'currencies/description/not_visited_countries'
    else
      render 'currencies/description/available_currencies'
    end
  end

  def countries_link(currency_name, label)
    if user_signed_in?
      link_to label, country_path(currency_name)
    else
      label
    end
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def currency_pages_class
    if ['currencies', 'countries'].include? controller_name
      'active'
    end
  end

  def trip_pages_class
    'active' if controller_name == 'trips'
  end

  def profile_pages_class
    'active' if controller_name == 'registrations'
  end
end

app/helpers/trips_helper.rb
module TripsHelper
  def countries(trip)
    trip.countries.map(&:name).to_sentence
  end

  def trip_dates(dates)
    dates.map { |d| I18n.l d, :format => :short }.join ' / '
  end
end

app/views/countries/index.html.haml
- title "#{@currency.name} / Countries"

%ul
  - for country in @countries
    %li= country.name

= link_to 'Back', currencies_path

app/views/countries/show.html.haml
- title "#{@currency_name} / Countries"

= form_for current_user, :url => country_path(@currency_name), :html => { :method => :put } do |form|
  = form.error_messages

  %ul.countries
    = form.fields_for :appointments, @appointments do |appointment_fields|
      %li
        = appointment_fields.check_box :country_id, *appointment_check_box_options(appointment_fields.object)
        = appointment_fields.label :country_id, country_label(appointment_fields.object.country)
        = appointment_fields.check_box :_destroy, { :class => 'delete' }, '1', ''

  .buttons
    = link_to 'Back', currencies_path
    = form.submit 'Save'

- javascript 'app/countries/show'

app/views/currencies/_list.html.haml
- if user_signed_in?
  .description= currency_description

%table
  %tr
    %th Currency
    %th Available countries
    - if user_signed_in?
      %th Not visited countries
  %tr
    - currencies.each do |currency|
      %tr
        %td= currency.name
        %td= countries_link currency.name, currency.available_country_count.to_i
        - if user_signed_in?
          %td= countries_link currency.name, currency.remaining_country_count.to_i

app/views/currencies/description/_available_currencies.html.haml
All available currencies.
= link_to 'Show currencies that still have countries to visit.', |
          remaining_currencies_path,                             |
          :class => 'dashed'

app/views/currencies/description/_not_visited_countries.html.haml
Currencies that still have countries to visit.
= link_to 'Show all available currencies.', currencies_path, :class => 'dashed'

app/views/currencies/index.html.haml
.description
  = currency_description

%table
  %tr
    %th Currency
    %th Available countries
    - if user_signed_in?
      %th Not visited countries
  %tr
    - @currencies.each do |currency|
      %tr
        %td= currency.name
        %td= currency.available_country_count.to_i
        - if user_signed_in?
          %td= currency.remaining_country_count.to_i

app/views/currencies/remaining.html.haml
= render 'currencies/list', :currencies => @currencies

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Currencies"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag :all, :recursive => true
    = javascript_include_tag :defaults
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      #navigation
        = render 'layouts/application/navigation'

      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/layouts/application/_navigation.html.haml
= link_to 'Currencies', currencies_path, :class => currency_pages_class

- if user_signed_in?
  = link_to 'Trips', trips_path, :class => trip_pages_class
  = link_to 'Profile', edit_user_registration_path, :class => profile_pages_class
  .login_menu
    = current_user.email
    = link_to 'Sign Out', destroy_user_session_path, :class => 'sign_in'
- else
  .login_menu
    = link_to 'Sign In', new_user_session_path, :class => 'sign_in'

app/views/trips/_form.html.haml
= form_for trip do |form|
  = form.error_messages
  %p
    = form.label :completed_at, 'Date'
    %br
    = form.text_field :completed_at, :class => 'date'
  %p
    = form.label :description
    %br
    = form.text_area :description, :size => '50x5'

  - if country_trips.any?
    = render 'trips/form/countries', :country_trips => country_trips, :form => form

  .buttons
    = link_to 'Back', trips_path
    = form.submit 'Save'

app/views/trips/form/_countries.html.haml
- country_trips.each_slice(country_trips.size / 2) do |collection|
  %ul.country_list
    = form.fields_for :country_trips, collection do |fields|
      %li
        = fields.check_box :country_id, { :checked => false }, fields.object.country_id, ''
        = fields.label :country_id, fields.object.country.name

app/views/trips/index.html.haml
%strong Visited countries:
= @summary[:visited_countries]
%br
%strong Dates:
= trip_dates(@summary[:dates])

#trips
  - @trips.each do |trip|
    .trip
      %h4= countries trip
      = trip.description
      .date=l trip.completed_at, :format => :long

= link_to "New Trip", new_trip_path

app/views/trips/new.html.haml
- title 'New Trip'

= render 'trips/form', :trip => @trip, :country_trips => @country_trips

- javascript 'jquery-ui-1.8.10.custom.min'
- javascript 'app/trips/new'